#!/bin/sh
# hawk = Hayes awk, by Wayne Hayes (whayes@uci.edu)
DIR="`dirname $0`"
TABS=false
if [ "$1" = -T ]; then
    TABS=true; shift
fi
PROG="$1"
shift
if $TABS; then
    exec gawk -F '	' "`cat "$DIR/misc.awk"`$PROG" "$@"
else
    exec gawk "`cat "$DIR/misc.awk"`$PROG" "$@"
fi
